id: AUTH-CONFIGURE-PASSWORD-INPUT-001
title: Password input fields must use type=password
severity: low
scope: web-application
requirement: Password input fields must use type=password to mask the entry. Applications
  may allow the user to temporarily view the entire masked password, or the last typed
  character of the password.
do:
- Use type=password for password input fields
dont:
- Use plain text input fields for passwords
detect:
  semgrep:
  - password-field-type
verify:
  tests:
  - Manually verify that password input fields are masked
refs:
  cwe:
  - CWE-312
  asvs:
  - V6.2.6
  owasp:
  - A2:2021