detect:
  semgrep:
  - yaml.docker-compose.security.writable-filesystem-service
  - terraform.aws.security.aws-s3-bucket-public-read-prohibited
do:
- Document all communication needs for the application
- Include external services and potential end user-provided locations
dont:
- Neglect documenting communication needs
id: CONFIG-SEC-004
refs:
  asvs:
  - V13.1.1
  cwe:
  - CWE-16
  owasp:
  - A05:2021
requirement: Ensure that all communication needs for the application are documented,
  including external services which the application relies upon and cases where an
  end user might be able to provide an external location to which the application
  will then connect.
scope: web-application
severity: medium
title: Document all communication needs and external services
verify:
  tests:
  - Review documentation for completeness
